
@API_URL = https://challenge.crossmint.io/api/
@candidateID = 1fa26b6a-4f79-48cb-bcde-788a3e29a112
###
POST {{API_URL}}polyanets
content-type: application/json

{
    "candidateId": "{{candidateID}}",
    "row":"8",
    "column":"8"
}

###
DELETE {{API_URL}}polyanets
content-type: application/json

{
    "candidateId": "{{candidateID}}",
    "row":"2",
    "column":"3"
}
###
POST {{API_URL}}comeths
content-type: application/json

{
    "candidateId": "{{candidateID}}",
    "row":"1",
    "column":"7",
    "direction":"right"
}
###
GET {{API_URL}}map/{{candidateID}}/goal